version: '2'

services:
  dockerizedspa:
    build: ./
    ports:
      - "8081:8081"
    links:
      - database
    volumes:
      - .:/usr/src/app
    depends_on:
      - database
      
  database: 
    image: mongo